#!/usr/bin/env python3
"""ACTS CLI - Operation invocation system."""

import sys
import os

# Add lib to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'lib'))

from cli import main

if __name__ == '__main__':
    sys.exit(main())
